name: "vocoder_bigvgan"
backend: "python"
max_batch_size: 0

parameters [
  {
    key: "model_dir"
    value: { string_value: "/models/BigVGAN/bigvgan_v2_24khz_100band_256x" }
  },
  {
    key: "bigvgan_module_dir"
    value: { string_value: "/workspace/F5-TTS/src/third_party/BigVGAN" }
  }
]

input [
  {
    name: "mel"
    data_type: TYPE_FP32
    dims: [ 100, -1 ]
  }
]

output [
  {
    name: "waveform"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
